backend:
  name: github
  repo: DDTCanal/site-ddtcanal
  branch: main
  base_url: https://pdt-auth.vercel.app # O seu servidor de login
  auth_endpoint: auth

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Matérias do Portal"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título da Matéria", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Capa (G1 Style)", name: "thumbnail", widget: "image" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Tecnologia", "Fones", "Games", "Vídeo"] }
      - { label: "Breve Descrição (Subtítulo)", name: "description", widget: "string" }
      - { label: "Texto da Matéria", name: "body", widget: "markdown" }
